# Generated by Django 5.1.3 on 2024-11-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('vaccinated', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('species', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('breed', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('vaccinated', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('vaccinated', models.BooleanField(default=False)),
                ('breed', models.IntegerField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exotic_Animal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('region_of_origin', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('type_of_animal', models.CharField(max_length=255)),
                ('vaccinated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('number_of_pets', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
