# Generated by Django 5.1.3 on 2024-11-14 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0002_alter_pokemon_description_alter_pokemon_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='Unknown Pokemon', validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(150)]),
        ),
    ]
