# Generated by Django 5.1.3 on 2024-11-14 16:08

import pokemon_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0003_alter_pokemon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=255, validators=[pokemon_app.validators.validate_pokemon_name]),
        ),
    ]
