# Generated by Django 5.1.4 on 2024-12-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
