# Generated by Django 5.1.3 on 2024-11-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('student_email', models.EmailField(max_length=255, unique=True)),
                ('personal_email', models.EmailField(max_length=255, null=True, unique=True)),
                ('locker_numer', models.IntegerField(default=1)),
                ('locker_combination', models.CharField(max_length=255)),
                ('good_student', models.BooleanField(default=False)),
            ],
        ),
    ]
