# Generated by Django 5.1.3 on 2024-11-15 16:08

import django.core.validators
import move_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[move_app.validators.validate_move_name])),
                ('accuracy', models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('pp', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)])),
                ('power', models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)])),
            ],
        ),
    ]
